Repository softcreations01/OAU-GDSC-CLOUD-Hacktoberfest_2023, pull requests merged in 2023-10, with the labels that each got.

#4 add contribution
  assests/images/kabby.jpeg
  index.html
  style.css
Labels: hacktoberfest, Hacktoberfest-accepted

#5 added contribution
  assests/images/ohohoh456.png
Labels: hacktoberfest, Hacktoberfest-accepted

#7 Added a project
  CODERS/CountryDataGenerator/index.html
  CODERS/CountryDataGenerator/main.js
  CODERS/CountryDataGenerator/style.css
Labels: hacktoberfest, team: coders, Hacktoberfest-accepted

#16 nodejs mini project
  CODERS/CartSimulator/index.js
  assests/images/Jonnie-Dev.png
  index.html
  style.css
Labels: hacktoberfest, team: coders, Hacktoberfest-accepted

#15 Update READEME.md
  NON-CODERS/READEME.md
Labels: hacktoberfest, Hacktoberfest-accepted

#9 Create CoinFlipperGame.py
  CODERS/CoinFlipperGame.py
Labels: team: coders, Hacktoberfest-accepted

#8 Create Dice_Roller.py
  CODERS/Dice_Roller.py
Labels: team: coders, Hacktoberfest-accepted

#20 Update CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: Hacktoberfest-accepted

#19 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Hacktoberfest-accepted

#18 kmalhotra08 Basketball Game
  CODERS/kmalhotra08 Basketball Game
Labels: Hacktoberfest-accepted

#13 New feature
  CODERS/Holy-grail/img/banner.png
  CODERS/Holy-grail/index.html
  CODERS/Holy-grail/style.css
  assests/images/logo.jpg
  index.html
  style.css
Labels: team: coders, Hacktoberfest-accepted

#23 Huffman coding
  CODERS/Huffman_Coding/Huffman.cpp
  CODERS/Huffman_Coding/Huffman.hpp
  CODERS/Huffman_Coding/commands_to_run.txt
  CODERS/Huffman_Coding/compressed.txt
  CODERS/Huffman_Coding/decompressed.txt
  CODERS/Huffman_Coding/main.exe
  CODERS/Huffman_Coding/sample.txt
  GUIDE_TO_RUN
Labels: team: coders, Hacktoberfest-accepted

#22 Added : A profile And Fix: Invalid comment line
  assests/images/harshit_pandey.jpg
  index.html
  style.css
Labels: hacktoberfest, Hacktoberfest-accepted

#24 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Hacktoberfest-accepted

#25 hacktoberfest
  calculator.py
Labels: team: coders

#27 fresh commit
  CODERS/CoinFlipperGame.py
  CODERS/Dice_Roller.py
  CODERS/cbt_system.py
  assests/images/JohnAdeolu.jpg
  index.html
  style.css
Labels: team: coders

#26 Password Generator project
  CODERS/password_generator/README.md
  CODERS/password_generator/password_generator.py
Labels: team: coders
